"""Competition API + dashboard integration.

These drive the real service and the real engine over a small synthetic tape. Nothing is mocked:
if a number appears in the dashboard it came through `metrics.compute` and `judge` exactly as the
CLI produces it.
"""
from __future__ import annotations

import dataclasses
import json

import pytest
from fastapi.testclient import TestClient

from app.competition import metrics as mx
from app.competition.service import CompetitionService, PROFILES, _downsample
from app.core.storage import Storage
from tests.conftest import T0, make_candles, settings_factory
from tests.test_competition import Idle, OneShot, big_rules

SYMBOL = "BTCUSDT"
AUTH = ("admin", "test-pw")
CSRF = {"X-PaperLab": "1"}


# ---- harness -------------------------------------------------------------------------------------

def seeded_storage(tmp_path, n=60):
    """A storage with a real candle window, the way the live feed backfills it."""
    st = Storage(str(tmp_path / "t.db"))
    closes = [100.0 * (1.004 ** i) for i in range(n)]
    st.insert_candles(make_candles(closes=closes, symbol=SYMBOL, tf="1m", start_ts=T0, wick=0.0))
    return st


def service(tmp_path, n=60):
    s = settings_factory(data_dir=str(tmp_path / "data"), SYMBOLS=SYMBOL)
    st = seeded_storage(tmp_path, n)
    return CompetitionService(s, st, {"T01": OneShot, "T02": Idle}, rules=big_rules()), st, s


async def run_season(svc, profile="realistic", **over):
    data = svc.data_report([SYMBOL])
    season = svc.build_season(symbols=[SYMBOL], start_ms=data["overlap_start_ms"],
                              end_ms=data["overlap_end_ms"], profile=profile, **over)
    run_id = await svc.start(season, profile)
    await svc._task
    return run_id


@pytest.fixture
def client(tmp_path, monkeypatch):
    """The real FastAPI app with the engine's boot stubbed out (it needs a venue), plus a service."""
    from app.core import engine_boot
    from tests.conftest import FakeFeed
    monkeypatch.setattr(engine_boot, "MarketFeed", FakeFeed)
    from app.main import create_app
    settings = settings_factory(data_dir=str(tmp_path / "data"), SYMBOLS=SYMBOL)
    app = create_app(settings)
    with TestClient(app) as c:
        c.auth = AUTH
        svc = app.state.competition
        svc.classes = {"T01": OneShot, "T02": Idle}
        svc.rules = big_rules()
        closes = [100.0 * (1.004 ** i) for i in range(60)]
        svc.storage.insert_candles(make_candles(closes=closes, symbol=SYMBOL, tf="1m",
                                                start_ts=T0, wick=0.0))
        yield c


# ---- 8: the GUI loads with no competition ----------------------------------------------------------

class TestEmptyState:
    def test_overview_reports_not_run_rather_than_failing(self, client):
        r = client.get("/api/competition")
        assert r.status_code == 200
        d = r.json()
        assert d["ok"] is True and d["ran"] is False
        assert d["progress"]["status"] == "idle"
        assert "data" in d and SYMBOL in d["data"]["symbols"]

    def test_leaderboard_is_empty_not_an_error(self, client):
        d = client.get("/api/competition/leaderboard").json()
        assert d["ran"] is False and d["rows"] == []

    def test_seasons_is_empty(self, client):
        assert client.get("/api/competition/seasons").json()["seasons"] == []

    def test_bot_detail_without_a_season_is_404(self, client):
        assert client.get("/api/competition/bots/T01").status_code == 404

    def test_dashboard_shell_still_serves(self, client):
        r = client.get("/")
        assert r.status_code == 200
        # the navigation is generated by app.js; the panels it switches between are in the shell
        assert 'id="nav"' in r.text and 'data-panel="competition"' in r.text
        for panel in ("live", "market", "activity", "health"):
            assert f'data-panel="{panel}"' in r.text, panel
        for js in ("stream.js", "competition.js", "live.js", "app.js"):
            assert f"/static/{js}" in r.text, js


# ---- 1,2,3: leaderboard is the real engine ----------------------------------------------------------

class TestLeaderboard:
    @pytest.mark.asyncio
    async def test_rows_carry_the_real_metrics(self, tmp_path):
        svc, st, _ = service(tmp_path)
        await run_season(svc)
        comps = st.competition_competitors(svc.latest_run_id)
        t01 = next(c for c in comps if c["strategy_id"] == "T01")
        assert t01["metrics"]["trades"] >= 1
        assert set(mx.CompetitorMetrics("x").to_dict()) <= set(t01["metrics"])

    @pytest.mark.asyncio
    async def test_state_matches_judge(self, tmp_path):
        from app.competition.config import QualificationConfig
        from app.competition.qualification import judge
        svc, st, _ = service(tmp_path)
        await run_season(svc)
        for c in st.competition_competitors(svc.latest_run_id):
            if not c.get("metrics"):
                continue
            m = mx.CompetitorMetrics("x")
            for k, v in c["metrics"].items():
                setattr(m, k, v)
            assert c["state"] == judge(m, QualificationConfig()).state

    @pytest.mark.asyncio
    async def test_gross_and_net_match_the_metrics_engine(self, tmp_path):
        svc, st, _ = service(tmp_path)
        await run_season(svc)
        c = st.competition_competitor(svc.latest_run_id, "T01")
        m = c["metrics"]
        rebuilt = m["gross_pnl"] - m["fees_paid"] - m["slippage_cost"] + m["funding_paid"]
        assert m["net_profit"] == pytest.approx(rebuilt, abs=1e-9)
        assert m["latency_cost"] + m["spread_cost"] + m["impact_cost"] == \
            pytest.approx(m["slippage_cost"], abs=1e-9)

    @pytest.mark.asyncio
    async def test_rank_is_separate_from_qualification(self, tmp_path):
        """The product concept: #1 by score can still be INSUFFICIENT_SAMPLE."""
        svc, st, _ = service(tmp_path)
        await run_season(svc)
        comps = [c for c in st.competition_competitors(svc.latest_run_id) if c.get("metrics")]
        top = min(comps, key=lambda c: c["rank"])
        assert top["rank"] == 1
        assert top["state"] != "QUALIFIED", "a one-month season cannot qualify anything"


# ---- 4,6,7: isolated accounts ------------------------------------------------------------------------

class TestBotDetail:
    @pytest.mark.asyncio
    async def test_returns_only_that_bots_account(self, tmp_path):
        svc, st, _ = service(tmp_path)
        await run_season(svc)
        a = st.competition_competitor(svc.latest_run_id, "T01")
        b = st.competition_competitor(svc.latest_run_id, "T02")
        assert all(f.get("position_id") for f in a["fills"])
        assert b["fills"] == [], "the idle bot has no ledger"
        assert b["metrics"]["ending_equity"] == pytest.approx(b["metrics"]["starting_equity"])

    @pytest.mark.asyncio
    async def test_one_bot_cannot_expose_another_ledger(self, tmp_path):
        svc, st, _ = service(tmp_path)
        await run_season(svc)
        a = st.competition_competitor(svc.latest_run_id, "T01")
        b = st.competition_competitor(svc.latest_run_id, "T02")
        ids = {f["id"] for f in a["fills"]} & {f["id"] for f in (b["fills"] or [])}
        assert ids == set()

    def test_unknown_bot_is_a_clean_404(self, client):
        client.post("/api/competition/run", json={}, headers=CSRF)
        r = client.get("/api/competition/bots/NOPE")
        assert r.status_code in (404, 503)
        assert r.json()["ok"] is False


# ---- 5: pagination ------------------------------------------------------------------------------------

class TestTradePagination:
    @pytest.mark.asyncio
    async def test_pages_do_not_overlap_and_cover_everything(self, tmp_path):
        svc, st, _ = service(tmp_path)
        await run_season(svc)
        c = st.competition_competitor(svc.latest_run_id, "T01")
        fills = c["fills"]
        assert fills, "expected a ledger to page through"
        page1 = fills[0:1]
        page2 = fills[1:2]
        assert page1 != page2 or len(fills) == 1

    def test_limit_is_capped(self, client):
        from app.core.api_competition import MAX_PAGE
        assert MAX_PAGE <= 500

    @pytest.mark.asyncio
    async def test_offset_and_limit_slice_the_ledger(self, tmp_path):
        svc, st, _ = service(tmp_path)
        await run_season(svc)
        c = st.competition_competitor(svc.latest_run_id, "T01")
        n = len(c["fills"])
        assert c["fills"][0:1] == c["fills"][:1]
        assert len(c["fills"][n:]) == 0


# ---- 9: unfinished stages ------------------------------------------------------------------------------

class TestValidationHonesty:
    @pytest.mark.asyncio
    async def test_unrun_stages_are_not_run_never_pass(self, tmp_path):
        svc, st, _ = service(tmp_path)
        await run_season(svc)
        c = st.competition_competitor(svc.latest_run_id, "T01")
        stages = set(c["qualification"]["evaluated_stages"])
        assert stages == {"season"}
        for missing in ("walk_forward", "monte_carlo", "stress"):
            assert missing not in stages

    @pytest.mark.asyncio
    async def test_nothing_reaches_qualified_without_the_later_stages(self, tmp_path):
        svc, st, _ = service(tmp_path)
        await run_season(svc)
        for c in st.competition_competitors(svc.latest_run_id):
            assert c["state"] not in ("QUALIFIED", "SHADOW_LIVE", "LIVE_CANDIDATE")


# ---- 10: the competition cannot arm live trading ---------------------------------------------------------

class TestLiveSafety:
    def test_no_competition_route_can_promote_or_arm(self):
        """No competition module may CALL a promotion or order-placing path.

        Parsed rather than grepped: both modules legitimately mention the operator path in prose
        ("promotion stays behind the GO LIVE arm phrase"), and a substring search would flag the
        docstring that documents the safety property it is checking.
        """
        import ast
        import inspect
        from app.competition import service as svc_mod
        from app.core import api_competition
        banned = {"promote", "demote", "live_arm", "arm_live", "place_order", "create_order",
                  "flatten_all", "set_live_strategies"}
        for mod in (api_competition, svc_mod):
            tree = ast.parse(inspect.getsource(mod))
            called = set()
            for node in ast.walk(tree):
                if isinstance(node, ast.Call):
                    fn = node.func
                    name = getattr(fn, "attr", None) or getattr(fn, "id", None)
                    if name:
                        called.add(name)
            assert not (called & banned), f"{mod.__name__} calls {sorted(called & banned)}"

    def test_service_holds_no_exchange_client(self, tmp_path):
        svc, _, _ = service(tmp_path)
        assert not hasattr(svc, "client")
        assert not hasattr(svc, "router")

    @pytest.mark.asyncio
    async def test_a_live_candidate_label_does_not_change_the_engine(self, tmp_path):
        svc, st, _ = service(tmp_path)
        await run_season(svc)
        # the competition writes only its own tables
        rows = st.conn.execute("SELECT COUNT(*) AS n FROM strategy_state").fetchone()
        assert rows["n"] == 0, "a season must not touch live strategy state"


# ---- 11,12: existing behaviour is intact ---------------------------------------------------------------

class TestExistingRoutesStillWork:
    def test_health_is_still_open_and_ok(self, client):
        r = client.get("/api/health")
        assert r.status_code == 200 and r.json()["ok"] in (True, False)

    def test_state_still_serves(self, client):
        assert client.get("/api/state").status_code == 200

    def test_strategies_still_serve(self, client):
        assert client.get("/api/strategies").status_code == 200

    def test_post_still_needs_the_csrf_header(self, client):
        assert client.post("/api/competition/run", json={}).status_code == 403

    def test_api_still_needs_auth(self, client):
        r = client.get("/api/competition", auth=("admin", "wrong"))
        assert r.status_code == 401


class TestProductionStartup:
    def test_dockerfile_still_binds_the_platform_port(self):
        from pathlib import Path
        df = Path("Dockerfile").read_text()
        assert "${PORT:-8080}" in df and "${BIND_HOST}" in df

    def test_procfile_binds_port(self):
        from pathlib import Path
        assert "$PORT" in Path("Procfile").read_text()

    def test_healthcheck_path_unchanged(self):
        from pathlib import Path
        cfg = json.loads(Path("railway.json").read_text())
        assert cfg["deploy"]["healthcheckPath"] == "/api/health"

    def test_dashboard_assets_are_all_referenced(self):
        from pathlib import Path
        html = Path("app/dashboard/index.html").read_text(encoding="utf-8")
        for asset in ("styles.css", "charts.js", "app.js", "competition.js"):
            assert asset in html


# ---- transport -------------------------------------------------------------------------------------------

class TestEquityDownsample:
    def test_keeps_the_endpoints_exactly(self):
        pts = [(i, float(i)) for i in range(5000)]
        out = _downsample(pts, 100)
        assert out[0] == (0, 0.0) and out[-1] == (4999, 4999.0)
        assert len(out) <= 102

    def test_short_curves_are_untouched(self):
        pts = [(1, 1.0), (2, 2.0)]
        assert _downsample(pts, 100) == pts


class TestProfiles:
    def test_legacy_profile_reproduces_the_old_execution(self):
        p = PROFILES["legacy"]
        assert p.total_latency_ms == 0 and p.vol_component == 0.0 and p.base_slippage_bps == 2.0

    def test_realistic_is_the_default_and_has_latency(self):
        assert PROFILES["realistic"].total_latency_ms == 400


class TestSeasonOwnsItsRiskConfig:
    """A Season's starting balance must be what the books actually start with.

    Regression: ReplayEngine sizes from `settings.strategy_starting_balance`, so a season built
    with RiskConfig(starting_balance=20) replayed at the server's env default (100) while the
    dashboard header truthfully quoted the season's 20. Caught in the GUI, not by the CLI, because
    the CLI builds its settings from the same --balance flag.
    """

    @pytest.mark.asyncio
    async def test_starting_balance_comes_from_the_season_not_the_environment(self, tmp_path):
        from app.competition.config import RiskConfig
        s = settings_factory(data_dir=str(tmp_path / "d"), SYMBOLS=SYMBOL, balance=100.0)
        st = seeded_storage(tmp_path)
        svc = CompetitionService(s, st, {"T01": OneShot}, rules=big_rules())
        assert s.strategy_starting_balance == 100.0
        d = svc.data_report([SYMBOL])
        season = svc.build_season(symbols=[SYMBOL], start_ms=d["overlap_start_ms"],
                                  end_ms=d["overlap_end_ms"], starting_balance=20.0)
        assert season.risk.starting_balance == 20.0
        rid = await svc.start(season, "realistic")
        await svc._task
        c = st.competition_competitor(rid, "T01")
        assert c["metrics"]["starting_equity"] == pytest.approx(20.0)

    @pytest.mark.asyncio
    async def test_risk_per_trade_also_follows_the_season(self, tmp_path):
        from app.competition.config import RiskConfig
        from app.competition.engine import CompetitionEngine
        s = settings_factory(data_dir=str(tmp_path / "d"), SYMBOLS=SYMBOL)
        st = seeded_storage(tmp_path)
        svc = CompetitionService(s, st, {"T01": OneShot}, rules=big_rules())
        d = svc.data_report([SYMBOL])
        season = svc.build_season(symbols=[SYMBOL], start_ms=d["overlap_start_ms"],
                                  end_ms=d["overlap_end_ms"], starting_balance=20.0)
        season = dataclasses.replace(season, risk=RiskConfig(starting_balance=20.0,
                                                            risk_per_trade_pct=0.01))
        eng = CompetitionEngine(s, season, rules=big_rules())
        assert eng._season_settings().risk_per_trade_pct == pytest.approx(0.01)
        assert eng._season_settings().strategy_starting_balance == pytest.approx(20.0)
