/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyzeRouteImport } from './routes/analyze'
import { Route as BotsRouteImport } from './routes/bots'
import { Route as ProgramsRouteImport } from './routes/programs'
import { Route as BotsIndexRouteImport } from './routes/bots.index'
import { Route as BotsBotIdRouteImport } from './routes/bots.$botId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyzeRoute = AnalyzeRouteImport.update({
  id: '/analyze',
  path: '/analyze',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsRoute = BotsRouteImport.update({
  id: '/bots',
  path: '/bots',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgramsRoute = ProgramsRouteImport.update({
  id: '/programs',
  path: '/programs',
  getParentRoute: () => rootRouteImport,
} as any)
const BotsIndexRoute = BotsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BotsRoute,
} as any)
const BotsBotIdRoute = BotsBotIdRouteImport.update({
  id: '/$botId',
  path: '/$botId',
  getParentRoute: () => BotsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/bots': typeof BotsRouteWithChildren
  '/programs': typeof ProgramsRoute
  '/bots/$botId': typeof BotsBotIdRoute
  '/bots/': typeof BotsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/programs': typeof ProgramsRoute
  '/bots/$botId': typeof BotsBotIdRoute
  '/bots': typeof BotsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analyze': typeof AnalyzeRoute
  '/bots': typeof BotsRouteWithChildren
  '/programs': typeof ProgramsRoute
  '/bots/$botId': typeof BotsBotIdRoute
  '/bots/': typeof BotsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/analyze' | '/bots' | '/programs' | '/bots/$botId' | '/bots/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/analyze' | '/programs' | '/bots/$botId' | '/bots'
  id:
    | '__root__'
    | '/'
    | '/analyze'
    | '/bots'
    | '/programs'
    | '/bots/$botId'
    | '/bots/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyzeRoute: typeof AnalyzeRoute
  BotsRoute: typeof BotsRouteWithChildren
  ProgramsRoute: typeof ProgramsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analyze': {
      id: '/analyze'
      path: '/analyze'
      fullPath: '/analyze'
      preLoaderRoute: typeof AnalyzeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots': {
      id: '/bots'
      path: '/bots'
      fullPath: '/bots'
      preLoaderRoute: typeof BotsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/programs': {
      id: '/programs'
      path: '/programs'
      fullPath: '/programs'
      preLoaderRoute: typeof ProgramsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bots/': {
      id: '/bots/'
      path: '/'
      fullPath: '/bots/'
      preLoaderRoute: typeof BotsIndexRouteImport
      parentRoute: typeof BotsRoute
    }
    '/bots/$botId': {
      id: '/bots/$botId'
      path: '/$botId'
      fullPath: '/bots/$botId'
      preLoaderRoute: typeof BotsBotIdRouteImport
      parentRoute: typeof BotsRoute
    }
  }
}

interface BotsRouteChildren {
  BotsBotIdRoute: typeof BotsBotIdRoute
  BotsIndexRoute: typeof BotsIndexRoute
}

const BotsRouteChildren: BotsRouteChildren = {
  BotsBotIdRoute: BotsBotIdRoute,
  BotsIndexRoute: BotsIndexRoute,
}

const BotsRouteWithChildren = BotsRoute._addFileChildren(BotsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyzeRoute: AnalyzeRoute,
  BotsRoute: BotsRouteWithChildren,
  ProgramsRoute: ProgramsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
